{
  "name": "atmospeak-pro-updates",
  "main": "src/index.ts",
  "compatibility_date": "2025-07-01",
  "workers_dev": true,
  "routes": [
    {
      "pattern": "updates.novpax.org/atmospeak/pro/*",
      "zone_name": "novpax.org"
    }
  ],
  "r2_buckets": [
    {
      "binding": "PRO_BUCKET",
      "bucket_name": "atmospeak-pro"
    }
  ]
}
