pub mod app_state;
pub mod asr_host;
pub mod backtrack;
pub mod cleanup;
pub mod dictation_engine;
pub mod injection;
pub mod live_paste;
pub mod llama_host;
pub mod metrics;
pub mod model_downloader;
pub mod overlay_window;
pub mod polish;
pub mod polish_models;
#[cfg(feature = "pro")]
pub mod polar_license;
#[cfg(feature = "pro")]
pub mod pro_commands;
pub mod proc;
pub mod recorder;
pub mod runtime;
pub mod shortcuts;
pub mod sound_check;
pub mod startup;
pub mod streaming_asr;
pub mod transcriber;
pub mod window_manager;
